# Generated by Django 6.0.6 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('data_extra', models.JSONField(blank=True, null=True)),
                ('leida', models.BooleanField()),
                ('enviada_push', models.BooleanField()),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
    ]
