# Generated by Django 6.0.6 on 2026-06-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_club_management_fields'),
        ('notifications', '0003_notificacion_club_notificacion_fecha_lectura_and_more'),
        ('users', '0002_usuarioclub'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='club',
            field=models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
