# Generated by Django 6.0.6 on 2026-06-22 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_convocatoria_hu11_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_key', models.CharField(blank=True, max_length=255, null=True)),
                ('video_nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('video_tamano', models.BigIntegerField(blank=True, null=True)),
                ('video_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('analisis_estado', models.CharField(choices=[('SIN_VIDEO', 'Sin Video'), ('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='SIN_VIDEO', max_length=50)),
                ('analisis_progreso', models.IntegerField(default=0)),
                ('analisis_error', models.TextField(blank=True, null=True)),
                ('analisis_iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('analisis_finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_analisis', to='sports.partido')),
            ],
            options={
                'db_table': 'video_partido',
            },
        ),
        migrations.CreateModel(
            name='InformeScouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('metricas_json', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_scouting', to='sports.partido')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.videopartido')),
            ],
            options={
                'db_table': 'informe_scouting',
            },
        ),
    ]
