# Generated by Django 6.0.6 on 2026-06-23 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_videopartido_informescouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRiesgoLesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=20)),
                ('motivo', models.TextField()),
                ('recomendacion', models.TextField()),
                ('score_riesgo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ATENDIDA', 'Atendida')], default='ACTIVA', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_lesion', to='sports.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_lesion', to='sports.jugador')),
            ],
            options={
                'db_table': 'alerta_riesgo_lesion',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
