# Generated by Django 6.0.6 on 2026-06-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_alertariesgolesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertariesgolesion',
            name='nivel_riesgo',
        ),
        migrations.AddField(
            model_name='alertariesgolesion',
            name='minutos_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertariesgolesion',
            name='nivel',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='alertariesgolesion',
            name='vista_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertariesgolesion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('VISTA', 'Vista')], default='ACTIVA', max_length=20),
        ),
    ]
