# Generated by Django 6.0.6 on 2026-06-23 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_remove_alertariesgolesion_nivel_riesgo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionAscenso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_actual', models.CharField(max_length=100)),
                ('categoria_recomendada', models.CharField(max_length=100)),
                ('score_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('analisis_considerados', models.IntegerField(default=0)),
                ('nivel', models.CharField(choices=[('TALENTO_DESTACADO', 'Talento Destacado'), ('LISTO_PARA_ASCENSO', 'Listo para Ascenso')], max_length=50)),
                ('motivo', models.TextField()),
                ('recomendacion', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('REVISADA', 'Revisada'), ('SEGUIMIENTO', 'Seguimiento')], default='ACTIVA', max_length=20)),
                ('accion_seguimiento', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_ascenso', to='sports.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_ascenso', to='sports.jugador')),
            ],
            options={
                'db_table': 'recomendacion_ascenso',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
