# Generated by Django 6.0.6 on 2026-06-19 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_club_management_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_url', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_jugadores', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_equipos', models.PositiveIntegerField(blank=True, null=True)),
                ('incluye_ia', models.BooleanField(default=False)),
                ('incluye_reportes', models.BooleanField(default=False)),
                ('soporte', models.CharField(max_length=100)),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plan_saas',
                'ordering': ['precio_mensual', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='suscripciones_saas', to='clubs.club')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='payments.plansaas')),
            ],
            options={
                'db_table': 'club_plan',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('club',), name='unique_active_plan_per_club')],
            },
        ),
    ]
