# Generated by Django 6.0.6 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_cuota_social_hu16'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubplan',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clubplan',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
