# Generated by Django 6.0.6 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaIa',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=100, null=True)),
                ('vista', models.BooleanField()),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'alerta_ia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalisisIa',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('resumen_tactico', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('metadata_modelo', models.JSONField(blank=True, null=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'analisis_ia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetricaIaJugador',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('pases_completados', models.IntegerField()),
                ('pases_fallidos', models.IntegerField()),
                ('duelos_ganados', models.IntegerField()),
                ('duelos_perdidos', models.IntegerField()),
                ('distancia_recorrida_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sprints', models.IntegerField()),
                ('heatmap_url', models.TextField(blank=True, null=True)),
                ('score_rendimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perfil_sugerido', models.CharField(blank=True, max_length=255, null=True)),
                ('compatibilidad_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas_ia', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'metrica_ia_jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('r2_key', models.CharField(max_length=255)),
                ('r2_url', models.TextField()),
                ('duracion_seg', models.IntegerField(blank=True, null=True)),
                ('tamanio_bytes', models.BigIntegerField(blank=True, null=True)),
                ('estado_analisis', models.CharField(max_length=100)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
